[package]
name = "browser"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.30", default-features = false, features = ["default_fonts", "wayland", "x11", "wgpu"] }
egui = "0.30"
env_logger = "0.11"
wgpu = "0.20"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["full"] }
